apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ingress-annotations-webhook
webhooks:
  - name: ingress.annotations.mutate.k8s.io
    rules:
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["ingresses"]
    clientConfig:
      service:
        name: k8smutatingwebhook-service
        namespace: default
        path: "/mutate-ingress"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwakNDQXJxZ0F3SUJBZ0lJUTFRY2gyZ1ZzbTB3RFFZSktvWklodmNOQVFFTEJRQXdiakVMTUFrR0ExVUUKQmhNQ1Rrd3hFREFPQmdOVkJBZ1RCMHhwYldKMWNtY3hFVEFQQmdOVkJBY1RDRkp2WlhKdGIyNWtNUXd3Q2dZRApWUVFLRXdOek0yUXhEREFLQmdOVkJBTVRBM016WkRFZU1Cd0dDU3FHU0liM0RRRUpBUllQYzJGbFpXUkFZV2RvClpHRnRMbTVzTUNBWERUSXpNVEF4TWpFd05EZ3dNRm9ZRHprNU9Ua3hNak14TWpJMU9UQXdXakJ1TVFzd0NRWUQKVlFRR0V3Sk9UREVRTUE0R0ExVUVDQk1IVEdsdFluVnlaekVSTUE4R0ExVUVCeE1JVW05bGNtMXZibVF4RERBSwpCZ05WQkFvVEEzTXpaREVNTUFvR0ExVUVBeE1EY3pOa01SNHdIQVlKS29aSWh2Y05BUWtCRmc5ellXVmxaRUJoCloyaGtZVzB1Ym13d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURTcm9DaUg0T3UKOTNqUUJYL0FsdW5JWWVrQVRyNHBrdGtOcFp0dUErcTk5SDBoQ25lWlJNWjNCVjRJaHZzd3Q5cFR4T3ZxS2c5dAovcHdMSW9id0hJRC92dWtsaWd5ZlZjRGV5aDV1bWx5cUJnMEE4Ni9oWHhoNFR6WVJET3BVUFFQdmhSWGRYRHF4CklndGhaa3JtRjYrcC9JMmFEZXVsSUZlbjNJbHFNVGtZWVdJTGM4d3J5blU3c09rU0s0d2F3L3dLb1p3UDRBeDUKY3pnTWlhYS9hSUxDb1lPZGFGdmg2ckVpb3lDMjRJSlFCb2phUHhnem82UGhVb0kyd3FXdndZSysrYzFzaUpmegpiRlVUYmcyak43ZUJhWkx4V0tGUnN2akZ2QjVNamxEQThobzZnTm1JNFYwbVgyVEorTVkyTVJmbnJVNWpQdk9ICnVsQXNQNzVidjlrQkFnTUJBQUdqY2pCd01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMMEcKRklvQmsvOStqQ3ZlTExIVSt0WjRXd0hZTUFzR0ExVWREd1FFQXdJQkJqQVJCZ2xnaGtnQmh2aENBUUVFQkFNQwpBQWN3SGdZSllJWklBWWI0UWdFTkJCRVdEM2hqWVNCalpYSjBhV1pwWTJGMFpUQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBVmFrRVhLNmcyMFE4Nit5bkVaclgrRTNGa0ZmbUFQOFQzdmFCU0RGMWo1TlY5N0Q5VFdJalNXQlIKa2R3eUg3VFdxRFlOK0VEeXZ2Qit3NnZSSUp0MlJmOG43dnUxSUJIaS9SbUJFd1VydWZaZXphcC8vQmV4RTYvSQoyL3VueDdvVmxKV2w3Z3g3SGpMN3U1S0wwMkM2VEs3Q3ZxQWlWbWp0aGdjQW13Znd2ekc1U3FocDhyRm05cEtjClEwaitXRE15TFowbGIrNVRYZ2FPWjNZSmM3ZGdHRG1BUGdWLzJ6NGNHcXNpS2dwWnZNODJacEZXa3hJdGdKYW0KWEVKNG12TUI0Y0thWDdlVnJ0V0M1YzdUYXRhOWdUUmdKeE50SjRnNTF1b2J2bmRwdVpMa0U5Vjc4cDFwRWNzcAo5VGcybDcwMXNTV2p2ckNwN25kQXlybnpQNzZVbmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
