apiVersion: v1
kind: ConfigMap
metadata:
  name: k8smutatingwebhook-cm
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: Development
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
