apiVersion: v1
kind: Service
metadata:
  name: k8smutatingwebhook-service
  namespace: default
spec:
  selector:
    app: k8smutatingwebhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001